apiVersion: v1
kind: ConfigMap
metadata:
  name: message-system-config
  namespace: chat-system
data:
  KAFKA_BOOTSTRAP_SERVERS: >-
    kafka-0.kafka-headless.chat-system.svc.cluster.local:9092,
    kafka-1.kafka-headless.chat-system.svc.cluster.local:9092,
    kafka-2.kafka-headless.chat-system.svc.cluster.local:9092
  REDIS_CLUSTER_NODES: >-
    redis-cluster-0.redis-cluster-headless.chat-system.svc.cluster.local:6379,
    redis-cluster-1.redis-cluster-headless.chat-system.svc.cluster.local:6379,
    redis-cluster-2.redis-cluster-headless.chat-system.svc.cluster.local:6379,
    redis-cluster-3.redis-cluster-headless.chat-system.svc.cluster.local:6379,
    redis-cluster-4.redis-cluster-headless.chat-system.svc.cluster.local:6379,
    redis-cluster-5.redis-cluster-headless.chat-system.svc.cluster.local:6379

  SOURCE_DB_URL: "jdbc:mysql://mysql-source.chat-system.svc.cluster.local:3306/chat?useSSL=false&allowPublicKeyRetrieval=true"
  REPLICA_DB_URL: "jdbc:mysql://mysql-replica.chat-system.svc.cluster.local:3306/chat?useSSL=false&allowPublicKeyRetrieval=true"
  SOURCE_MESSAGE1_DB_URL: "jdbc:mysql://mysql-source-message1.chat-system.svc.cluster.local:3306/chat?useSSL=false&allowPublicKeyRetrieval=true"
  REPLICA_MESSAGE1_DB_URL: "jdbc:mysql://mysql-replica-message1.chat-system.svc.cluster.local:3306/chat?useSSL=false&allowPublicKeyRetrieval=true"
  SOURCE_MESSAGE2_DB_URL: "jdbc:mysql://mysql-source-message2.chat-system.svc.cluster.local:3306/chat?useSSL=false&allowPublicKeyRetrieval=true"
  REPLICA_MESSAGE2_DB_URL: "jdbc:mysql://mysql-replica-message2.chat-system.svc.cluster.local:3306/chat?useSSL=false&allowPublicKeyRetrieval=true"
