input {
    file {
        path => "/usr/share/logstash/logs/gateway/gateway-log*"
        start_position => "beginning"
        stat_interval => 1
        type => "gateway"
    }

    file {
        path => "/usr/share/logstash/logs/auth/auth-log*"
        start_position => "beginning"
        stat_interval => 1
        type => "auth"
    }

    file {
        path => "/usr/share/logstash/logs/user/user-log*"
        start_position => "beginning"
        stat_interval => 1
        type => "user"
    }
}

filter {
  grok {
    match => {
      "message" => "%{TIME:log_time} \{%{DATA:thread}\} %{LOGLEVEL:level}\s+%{DATA:logger} - %{GREEDYDATA:log_message}"
    }
  }
}

output {
    # elasticsearch 플러그인 → elasticsearch 적재 관련
    elasticsearch{
        hosts => ["http://elasticsearch:9200"]
        index => "%{type}-log.%{+YYYY-MM-dd}"
        ssl_verification_mode => none
    }

    stdout {
        codec => rubydebug
    }
}