spring:
  application:
    name: web-gateway
  cloud:
    config.enabled: false
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:8080'
            allowCredentials: true
            allowedHeaders: '*'
            allowedMethods: '*'

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
        - name: LoggingFilter
          args:
            baseMessage: Spring Cloud Gateway Filter
            preLogger: true
            postLogger: true

      routes:
        - id: message-auth
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/auth/**

        - id: websocket-route-message
          uri: ws://localhost:8090/
          predicates:
            - Path=/ws/v1/message
          filters:
            - AuthorizationHeaderFilter

### jwt
security.jwt:
  secret-key: 1234
  expiration-time: 3600000

### logging
logging:
  level:
    org.springframework.cloud.gateway: info
    reactor.netty: info